service: adhan-slack-app

plugins:
  - serverless-plugin-typescript
  - serverless-offline

custom:
  schedule_enabled:
    prod: true

  schedule:
    name: 'adhan-slack-app-daily-scheduler-${sls:stage}'
    description: 'scan users and reschedule messages each day'
    rate: cron(0,30 * * * ? *)
    enabled: ${self:custom.schedule_enabled.${sls:stage}}

provider:
  name: aws
  runtime: nodejs18.x
  stage: prod
  environment:
    SLACK_SIGNING_SECRET: ${env:SLACK_SIGNING_SECRET}
    SLACK_CLIENT_ID: ${env:SLACK_CLIENT_ID}
    SLACK_CLIENT_SECRET: ${env:SLACK_CLIENT_SECRET}
    SLACK_STATE_SECRET: ${env:SLACK_STATE_SECRET}
    CRYPTO_SECRET: ${env:CRYPTO_SECRET}
    CRYPTO_SALT: ${env:CRYPTO_SALT}
    MONGODB_URI: ${env:MONGODB_URI}

functions:
  slack-cron:
    handler: src/serverless/slack-cron.handler
    events:
      - schedule: ${self:custom.schedule}
  slack-handler:
    handler: src/serverless/slack-handler.handler
    events:
      - httpApi:
          method: post
          path: /slack/events
      - httpApi:
          method: get
          path: /slack/install
      - httpApi:
          method: get
          path: /slack/oauth_redirect
